### ISSUE TITLE
Error building contracts `v2.1` Docker images

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/contracts#390]
The contract docker images `v2.1.0` are not building on Docker Hub:
https://hub.docker.com/repository/registry-1.docker.io/neverminedio/geth-localnet/builds/954f4242-be0c-4a1b-8e4b-792a39c643a1

I could reproduce the same error locally:

```
Done in 0.70s.
yarn run v1.22.19
$ hardhat compile
Downloading compiler 0.8.9
Done in 1.25s.
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:798:11)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at output (/nevermined-contracts/node_modules/hardhat/src/internal/solidity/compiler/index.ts:79:22)
    at new Promise (<anonymous>)
    at NativeCompiler.compile (/nevermined-contracts/node_modules/hardhat/src/internal/solidity/compiler/index.ts:64:34)
    at SimpleTaskDefinition.action (/nevermined-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:639:37)
The command '/bin/sh -c /nevermined-contracts/scripts/keeper_deploy_geth_dockerfile.sh' returned a non-zero code: 1
```

The problem looks running the command:

```
npx hardhat run scripts/setup-geth.js --network geth-setup
```

**Comment by mrsmkl** [comment]
The problem is in the hardhat solc compiler, the native solc isn't compatible with alpine...
